[project]
name = "competitiveprogrammingcpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mypy>=1.16.0",
    "online-judge-verify-helper>=5.6.0",
    "pytest>=8.4.0",
]
